-- Migration 001: users table
-- TODO Sprint 1: crear tabla users con los campos necesarios.
-- Campos mínimos esperados:
--   id UUID PRIMARY KEY DEFAULT uuid_generate_v4()
--   email TEXT UNIQUE NOT NULL
--   password_hash TEXT NOT NULL  ← Argon2id, nunca texto plano
--   role TEXT NOT NULL CHECK (role IN ('owner', 'operator', 'client'))
--   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
--   updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- + trigger update_updated_at_column()
-- + CHECK de formato de email básico
-- NUNCA almacenar: contraseña en texto plano, token de sesión, datos de tarjeta.
